# -*- coding: utf-8 -*-
"""Machine Learning.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13GwpvVXkbPS6zrXer0ULzoEeegwy6h_S

# **⭐ Regression Model to Predict Cement Compressive Strength**

# import library
import pandas as pd

# import data
cement = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Concrete%20Compressive%20Strength.csv')

# view data
cement.head()

# info of data
cement.info()

# summary statistics
cement.describe()

# check for missing value
print(cement.isnull().sum(),'\n')

# check for categories
cement.nunique()

# visualize pairplot
from seaborn.axisgrid import PairGrid
import seaborn as sns
import matplotlib.pyplot as plt
sns.pairplot(cement);

# columns name
cement.columns

# define y
y = ['Concrete Compressive Strength(MPa, megapascals)']

# define X
X = [['Cement (kg in a m^3 mixture)', 'Blast Furnace Slag (kg in a m^3 mixture)',
      'Fly Ash (kg in a m^3 mixture)', 'Water (kg in a m^3 mixture)',
      'Superplasticizer (kg in a m^3 mixture)', 'Coarse Aggregate (kg in a m^3 mixture)',
      'Fine Aggregate (kg in a m^3 mixture)', 'Age (day)'
      ]]

# verify shape
X_train.shape, X_test.shape, y_train.shape, y_test.shape

# split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# train model
model.fit(X_train, y_train)

# predict with model
y_pred = model.predict(X_test)

# model evaluation
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

# model MAE
mean_absolute_error(y_test,y_pred)

# model MAPE
mean_squared_error(y_test, y_pred)

# model MSE
mean_squared_error(y_test, y_pred)

# future prediction
cement.sample()

# define X_new
X_new = X.sample()
X_new
X_new.values

# predict for X_new
model.predict(X_new)
